@url=http://127.0.0.1:5000

### Verbose BAD Request
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "assessment_tobacco_use": "Yes",
  "medical_prescreen_activity": "Yes"
}

### Minimal BAD Request
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Sled",
    "Treadmill"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [
    "Bands"
  ],
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness",
    "fainting",
    "blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

###
GET {{url}}/sample/request

###
GET {{url}}/sample/response

### Beginner Pathway No Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Beginner Pathway Basic Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Sled",
    "Treadmill"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Intermediate Pathway No Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Sled",
    "Treadmill"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Intermediate Pathway Basic Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Sled",
    "Treadmill"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Intermediate Pathway Gym Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Low Energy"
}

### Advanced Pathway No Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Advanced Pathway Gym Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Lift arms straight above your head",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "Yes",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Low Energy"
}

### Regressed/Beginner Painful ALL, Equipment ALL
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_painful_movements": ["None of them"],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Low Energy"
}

### Regressed/Beginner Painful ALL, Barbell Only
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [
    "Barbell only"
  ],
  "assessment_painful_movements": ["None of them"],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "No",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Home",
  "workout_motivation": "Low Energy"
}

### Regressed/Intermediate Painful SQUAT + LUNGE
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "Barbell only",
    "Dumbbells",
    "Kettlebells"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lift arms straight above your head",
    "Pushup"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Low Energy"
}

### Regressed/Intermediate Painful Raise, All Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Low Energy"
}

### Regressed/Intermediate Painful Raise, All Equipment, Motivated
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Pushup",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Motivated"
}

### Regressed/Intermediate Painful Raise, Push All Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Squat"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Pretty Good"
}

### Regressed/Intermediate Painful Push All Equipment
POST {{url}}/generate/workout
Accept: application/json
Content-Type: application/json

{
  "assessment_balance_left": "No",
  "assessment_balance_right": "No",
  "assessment_exercise_confidence": 1,
  "assessment_gym_equipment": [
    "All of them"
  ],
  "assessment_height_inches": 72,
  "assessment_home_equipment": [],
  "assessment_painful_movements": [
    "Lunge (Left v. Right)",
    "Squat",
    "Lift arms straight above your head"
  ],
  "assessment_run_mile": "No",
  "assessment_tobacco_use": "Yes",
  "assessment_walk_miles": "Yes",
  "assessment_weight_lbs": 180,
  "medical_prescreen_90_day_regularity": "No",
  "medical_prescreen_activity": "Yes",
  "medical_prescreen_ailments": [
    "heart failure",
    "diabetes"
  ],
  "medical_prescreen_symptoms": [
    "dizziness, fainting, blackouts"
  ],
  "onboarding_dob": "2022-09-09",
  "onboarding_gender": "Female",
  "workout_location": "Gym",
  "workout_motivation": "Pretty Good"
}

###